import os

DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://postgres:postgres@localhost:5432/mycelium")
GITHUB_CLIENT_ID = os.getenv("GITHUB_CLIENT_ID", "MOCK_CLIENT_ID")
GITHUB_CLIENT_SECRET = os.getenv("GITHUB_CLIENT_SECRET", "MOCK_CLIENT_SECRET")
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY", "SUPER_SECRET_HMAC_KEY_FOR_JWT_SIGNING")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60
